version: 0.2

phases:

  install:

    runtime-versions:

      python: 3.9

    commands:

      - SOURCE_VERSION=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - pip3 install --upgrade pip

      - pip3 install --upgrade awscli aws-sam-cli

      - pip3 install -r requirements.txt


  build:

    commands:
